modLoader="javafml"
loaderVersion="[46,)"
issueTrackerURL="https://github.com/Mrbysco/armor-poser/issues"
license="MIT"

[[mods]]
modId="armorposer"
version="${file.jarVersion}"
displayName="Armor Poser"
displayURL="https://www.curseforge.com/minecraft/mc-mods/armor-poser"
authors="Mrbysco"
credits="crazysnailboy for the original mod"
description='''
A GUI to allow configuration of Armor Stand properties
'''
[[dependencies.armorposer]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"
ordering="NONE"
side="BOTH"