modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/Mrbysco/armor-poser/issues"
license="MIT"

[[mods]]
modId="armorposer"
version="${file.jarVersion}"
displayName="Armor Poser"
displayURL="https://www.curseforge.com/minecraft/mc-mods/armor-poser"
authors="Mrbysco"
logoFile="icon.png"
credits="crazysnailboy for the original mod"
description='''
A GUI to allow configuration of Armor Stand properties
'''
[[dependencies.armorposer]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.armorposer]]
modId="neoforge"
type="REQUIRED"
versionRange="[20.4.70-beta,)"
ordering="NONE"
side="BOTH"