modLoader="javafml"
loaderVersion="[3,)"
issueTrackerURL="https://github.com/Mrbysco/armor-poser/issues"
license="MIT"

[[mods]]
modId="armorposer"
version="${file.jarVersion}"
displayName="Armor Poser"
displayURL="https://www.curseforge.com/minecraft/mc-mods/armor-poser"
authors="Mrbysco, ShyNieke"
logoFile="icon.png"
credits="crazysnailboy for the original mod"
description='''
A GUI to allow configuration of Armor Stand properties
'''
[[dependencies.armorposer]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.5,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.armorposer]]
modId="neoforge"
type="REQUIRED"
versionRange="[20.5.0-beta,)"
ordering="NONE"
side="BOTH"
[[mixins]]
config="armorposer.neoforge.mixins.json"